### PR TITLE
Use defined variable to set burp service name

### PR DESCRIPTION
**Pull request by kronos-pbrideau**

### CODE REVIEW

**Comment by tobru** [comment]
Thanks for your PR. I guess it would make more sense like this:

```
     service { $service_name:
       ensure => running,
       enable => true,
     }
```

**Comment by kronos-pbrideau** [comment]
Well, using a universal service name is usefull when ordering outside of this class

**Comment by kronos-pbrideau** [comment]
ref: https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/service.pp#L44

**Comment by tobru** [comment]
Makes sense. Thanks for the PR

**Pull request merged**
